In [1]:
import pandas as pd

In [3]:
date_columns = [
    "cookie_created_at",
    "window_start_ts",
    "window_end_ts",
]

train = pd.read_csv("data/train.csv", parse_dates=date_columns)
test = pd.read_csv("data/test.csv", parse_dates=date_columns)
events = pd.read_csv("data/events.csv.gz", compression="gzip", parse_dates=["event_ts"])

In [7]:
train.shape, train.dtypes

((11091, 5),
 cookie_id                       str
 cookie_created_at    datetime64[us]
 window_start_ts      datetime64[us]
 window_end_ts        datetime64[us]
 target                        int64
 dtype: object)

In [10]:
train.head()

,cookie_id,cookie_created_at,window_start_ts,window_end_ts,target
0,ck_54a059eb7d3ea68b,2025-11-21 09:30:41,2026-04-06,2026-04-07,0
1,ck_7e4de46eeab82974,2025-09-23 10:10:24,2026-04-06,2026-04-07,0
2,ck_9320229ef6304522,2026-03-04 00:08:02,2026-04-06,2026-04-07,0
3,ck_30ccd25bc1714ed9,2026-04-05 10:52:40,2026-04-06,2026-04-07,0
4,ck_a77c5f05948cdeef,2026-01-01 03:54:35,2026-04-06,2026-04-07,0

In [8]:
test.shape, test.dtypes

((4909, 4),
 cookie_id                       str
 cookie_created_at    datetime64[us]
 window_start_ts      datetime64[us]
 window_end_ts        datetime64[us]
 dtype: object)

In [11]:
test.head()

             cookie_id   cookie_created_at window_start_ts window_end_ts
0  ck_315fb710a0e371e7 2026-02-20 08:52:31      2026-04-20    2026-04-21
1  ck_a76ee3b3e3e522fd 2026-01-19 13:42:15      2026-04-20    2026-04-21
2  ck_94c9a4d382689e82 2026-04-19 06:28:37      2026-04-20    2026-04-21
3  ck_8eaf9509ad9462a0 2026-01-19 17:18:06      2026-04-20    2026-04-21
4  ck_9a88a5a989cb5bc6 2025-11-09 17:25:13      2026-04-20    2026-04-21

In [9]:
events.shape, events.dtypes

((328905, 14),
 cookie_id                   str
 event_ts         datetime64[us]
 eid                       int64
 event_name                  str
 platform                    str
 user_agent                  str
 item_id                 float64
 item_category               str
 item_location               str
 seller_type                 str
 search_query                str
 search_page             float64
 pointer_x               float64
 pointer_y               float64
 dtype: object)

In [12]:
events.head()

,cookie_id,event_ts,eid,event_name,platform,user_agent,item_id,item_category,item_location,seller_type,search_query,search_page,pointer_x,pointer_y
0,ck_5efbea1befdefe1b,2026-04-26 09:11:24,200,item_view,desktop,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,1027450.0,elektronika,kaliningrad,pro,NaN,NaN,NaN,NaN
1,ck_c4ca1434f3778f1d,2026-04-20 14:04:31,100,search_results_view,web,Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:1...,NaN,telefony,habarovsk,NaN,iphone 13 128,4.0,NaN,NaN
2,ck_d274382b19488771,2026-04-13 12:02:56,200,item_view,WEB,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,1048743.0,kvartiry_prodazha,kirov,private,NaN,NaN,675.0,276.0
3,ck_fbbed2ff14944ce9,2026-04-08 06:12:14,100,search_results_view,web,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,NaN,bytovaya_tehnika,novosibirsk,NaN,пылесос dyson,2.0,NaN,NaN
4,ck_56cc15c7c634cb9f,2026-04-12 17:16:05,100,search_results_view,WEB,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7...,NaN,odezhda,sankt-peterburg,NaN,костюм мужской,2.0,NaN,NaN

In [15]:
events.isna().sum()

cookie_id             0
event_ts              0
eid                   0
event_name            0
platform              0
user_agent            0
item_id          114597
item_category     32920
item_location     23793
seller_type      133853
search_query     228503
search_page      228503
pointer_x        220365
pointer_y        220365
dtype: int64